[package]
name = "fluent-uri"
version = "0.2.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"
description = "An RFC 3986 compliant generic URI parser and builder"
documentation = "https://docs.rs/fluent-uri"
repository = "https://github.com/yescallop/fluent-uri-rs"
license = "MIT"
keywords = ["builder", "parser", "uri", "rfc3986"]
categories = ["encoding", "parser-implementations"]

[features]
default = ["net", "std"]
# TODO: Remove std from net when ip_in_core is stablized in 1.77.0.
# Remember to add feature("std") to Authority::to_socket_addrs.
net = ["std"]
std = []

[dependencies]
borrow-or-share = "0.1"
ref-cast = "1.0"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
