[package]
name = "fluent-uri"
version = "0.1.2"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"
description = "A URI parser that strictly adheres to IETF RFC 3986"
repository = "https://github.com/yescallop/fluent-uri-rs"
license = "MIT"
keywords = ["parser", "uri"]
categories = ["encoding", "parser-implementations"]

[dependencies]
beef = "0.5.1"

[features]
ipv_future = []

[package.metadata.docs.rs]
all-features = true

# Commented out to reduce compile time.

# [[bench]]
# name = "bench"
# harness = false

# [dev-dependencies]
# criterion = "0.3"
# url = "2.2.2"
# uriparse = "0.6.4"
# iri-string = "0.5.0"
