[package]
name = "fluent-uri"
version = "0.2.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"
description = "An RFC 3986 compliant generic URI parser"
documentation = "https://docs.rs/fluent-uri"
repository = "https://github.com/yescallop/fluent-uri-rs"
license = "MIT"
keywords = ["parser", "uri", "rfc3986"]
categories = ["encoding", "parser-implementations"]

[features]
default = ["std"]
std = []
