[package]
name = "fluent-uri"
version = "0.2.0-alpha.4"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"
rust-version = "1.65"
description = "A fast, easy generic URI parser and builder compliant with RFC 3986."
documentation = "https://docs.rs/fluent-uri"
repository = "https://github.com/yescallop/fluent-uri-rs"
license = "MIT"
keywords = ["builder", "parser", "uri", "rfc3986"]
categories = ["encoding", "parser-implementations"]

[features]
default = ["net", "std"]
net = []
std = []

[dependencies]
borrow-or-share = "0.2"
ref-cast = "1.0"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
